travis:
  secure:
    BINSTAR_TOKEN: AXZbYyMhltnUNEREDSqOrV/p1VWFXa1XJ1AW63TocXWJE64Eawh2sMNOxc5S5VRJ0aeUJeIyiSXCwrT9RXIYIuuSdXRF3G5M6IcWyOA64nJ+FZwgHB8apb9u6YxLktfooWSZlEjH0zzWbCXU4ybaoXQMh8+8I4px7LCVGpr2OZWR2rTltDVSlWc3IS43fNfj6B+9fNP+B1glT5kjylyEMqudQIqh8jYMcpPdpicuiaZf2lDRAUhHjKvAGl/mkjo10uDX0OUz5iF8MbpV5KFxsF4xVXZknXThtRRGQm2YTFbJOJeSKBmBRga+b2ssCeFCrZ/sjuqBCVEWDejoVlOAwUq1lr6Wi0pRMz9FYKEEguTXlUBpcnqmz+7qeH11MvveyF5CuWOnWVQ/jtEVe0QRdr+c7lIY6AiQmFkjm7u+EqKay42Vr8DAc80VX5VoVfscYzwocZiqRYTnUp/+vi+wVGpxFBTe30gFUOiEADTnGi4A7rFgKG6jfipO0qXGUgrvtAwgkf8HTpOQsiGwD5/Z5l+2773xMmj4FJo+c8gcpOjPvriWelOtdjLFi53Tkha5gm7vv6aGyFbV1giH8Y4crV32TvsVNfvznpGB7ZP884WiGcap6n+biNIZF8nXRrg3cq3EAU5IvhN9qbrcQ/Mup6fcmpQfvvVce3J+M2n7//0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
